spring.application.name: demo

client-openai:
  key: ${OPENAI_API_KEY}
  endpoint: ${OPENAI_API_ENDPOINT}
  deployments-list-path: /openai/deployments
  deployment-name: ${OPENAI_DEPLOYMENT_NAME}

weather-api:
  key: ${WEATHER_API_KEY}
  endpoint: ${WEATHER_API_ENDPOINT}

pinecone:
  key: ${PINECONE_KEY}
  index-name: ${INDEX_NAME}
  similarity-metric: ${SIMILARITY_METRIC}
  dimension: ${DIMENSION}
  cloud-provider: ${CLOUD_PROVIDER}
  region: ${REGION}
  namespace: ${PINECONE_NAMESPACE}

embedding:
  model: ${EMBEDDING_MODEL}
  topK: ${TOP_K}